# Generated by Django 4.1.7 on 2023-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
