# Generated by Django 4.1.7 on 2023-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
