# Generated by Django 4.1.7 on 2023-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_total_quantity_order_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
