# Generated by Django 4.1.7 on 2023-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_recommendation_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
