# Generated by Django 4.1.7 on 2023-03-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_recommendation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books_images'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books_images'),
        ),
    ]
