# Generated by Django 4.1.7 on 2023-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('street', models.CharField(max_length=64)),
                ('house', models.SmallIntegerField(default=1)),
                ('corps', models.SmallIntegerField(default=1)),
                ('postal', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['id'],
            },
        ),
    ]
