# Generated by Django 4.1.7 on 2023-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0)),
                ('product_id', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField()),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
