# Generated by Django 4.1.7 on 2023-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_alter_basket_name_alter_basket_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
