# Generated by Django 4.1.7 on 2023-03-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_alter_basket_message_alter_basket_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='product_id',
            new_name='book_id',
        ),
    ]
