# Generated by Django 4.1.7 on 2023-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0004_rename_product_id_basket_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
