# Generated by Django 4.1.7 on 2023-03-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0005_basket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
